#  Array Attributes

In [3]:
import numpy as np

In [4]:
a1 = [1,2,3,4,5,6,7,8,9,10]
a1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
print(type(a1))

<class 'list'>


In [6]:
arr1 = np.array(a1)

In [7]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(type(arr1))

<class 'numpy.ndarray'>


In [9]:
# dimension of array
arr1.ndim

1

In [10]:
# shape of array
arr1.shape

(10,)

In [11]:
# size of array
arr1.size

10

In [12]:
# data types
arr1.dtype

dtype('int32')

In [13]:
a1 = [1.1,2,3,4,5,6,7,8,9,10]
a1
arr2 = np.array(a1)
arr2

array([ 1.1,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ])

In [14]:
arr2.dtype

dtype('float64')

# creating arrays

In [16]:
a2 = [1,2,3,4,5,6,7,8,9]
arr3 = np.array(a2)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr3 = np.arange(15,50) #start , stop (last value is not included)
arr3

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49])

In [20]:
arr3 = np.arange(15,51,5) #using step size
arr3

array([15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
arr3 = np.arange(15,51,.5) #using step size in fraction
arr3

array([15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ,
       20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5,
       26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. ,
       31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5,
       37. , 37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. ,
       42.5, 43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5,
       48. , 48.5, 49. , 49.5, 50. , 50.5])

In [22]:
arr3.size

72

In [27]:
arr4 =  np.linspace(1,10,10) #end value is included
arr4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
arr5 =  np.arange(1,10,10)
arr5

array([1])

In [ ]:
np.linspace

# 2d Array

In [ ]:
# HW
# create array using array() method from numpy
# find the data type of the new array created
1. a = ['A', 'E', 'I', 'O', 'U']
2. b = [1,2,3,4,5,'A']
3. c = [1,2,3,3.3,"E"]

# find attributes like dim,shape,size,data type of below arrays 
1. arr1 = np.linspace(0,1,10)
2. arr2 = np.array(['A', 'E', 'I', 'O', 'U'])
3. arr3 = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11]])


In [47]:
a = ['A', 'E', 'I', 'O', 'U']
b = [1,2,3,4,5,'A']
c = [1,2,3,3.3,"E"]

In [48]:
import numpy as np

In [53]:
arr1 = np.array(a)
print(arr1)
print(arr1.dtype)

['A' 'E' 'I' 'O' 'U']
<U1


In [55]:
arr1.dtype

dtype('<U1')

In [56]:
arr2 = np.array(b)
print(arr2)
print(arr2.dtype)

['1' '2' '3' '4' '5' 'A']
<U11


In [57]:
arr3 = np.array(c)
print(arr3)
print(arr3.dtype)

['1' '2' '3' '3.3' 'E']
<U32


In [58]:
arr1 = np.linspace(0,1,10)
arr2 = np.array(['A', 'E', 'I', 'O', 'U'])
arr3 = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11]])

In [59]:
arr1.ndim

1

In [60]:
arr1.shape

(10,)

In [61]:
arr1.size

10

In [62]:
arr1.dtype

dtype('float64')

In [63]:
arr3.ndim

2

In [64]:
arr3.shape

(3, 4)

In [65]:
arr3.size

12

In [66]:
arr3.dtype

dtype('int32')