# more on 2d arrays

In [1]:
import numpy as np

In [2]:
arr1  = np.arange(6)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5])

In [4]:
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
arr1.reshape(1,6) #row vector

array([[0, 1, 2, 3, 4, 5]])

In [7]:
arr1.reshape(6,1) #column vctor

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr1.reshape(1,-1) #numpy will replace -1 by 6 in the background for us

1*6
6*1
2*3
3*2

6

In [13]:
arr1.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [15]:
arr1.reshape(3,-1)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
# arr1.reshape(-1,-1) #this will give you error

# Initial Placeholders

In [21]:
# zeros

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros([4,3]) # for 2d arrays

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros([3,4,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
# ones

In [27]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [28]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.ones([1,6])

array([[1., 1., 1., 1., 1., 1.]])

In [30]:
np.ones([6,1])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [32]:
# identiity matrix

In [33]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
# diag

In [37]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# indexing and Slicing

In [62]:
#  with 1d array

In [43]:
arr2 = np.arange(5,12)

In [44]:
arr2

array([ 5,  6,  7,  8,  9, 10, 11])

In [45]:
arr2[2] #o/p 7

7

In [46]:
arr2[6]

11

In [47]:
arr2[-1]

11

In [48]:
arr2[0:3] #5,  6,  7

array([5, 6, 7])

In [50]:
arr2[4:]

array([ 9, 10, 11])

In [51]:
arr2[:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [52]:
# with 2d arrays

In [54]:
arr3 = np.arange(15).reshape(5,3)

In [55]:
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [56]:
arr3[0]

array([0, 1, 2])

In [57]:
arr3[1]

array([3, 4, 5])

In [58]:
arr3[4]

array([12, 13, 14])

In [59]:
arr3[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
arr3[0:]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [61]:
arr3[3:]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [65]:
arr3[3,0]

9