#  Indexing contd..

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(15).reshape(5,3)

In [3]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [6]:
arr1[0]

array([0, 1, 2])

In [7]:
arr1[3]

array([ 9, 10, 11])

# Slicing

In [9]:
arr1[0][0] # arr1[x][y] #arry[rows][column]

0

In [10]:
arr1[0][1]

1

In [11]:
arr1[2][1]

7

In [14]:
# arr1[0:3][0:1]

In [17]:
arr1[2,1] # same as arr1[2][1]

7

In [18]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
arr1[3,1]

10

In [20]:
arr1[2,2]

8

In [21]:
arr1[0:3,0:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [26]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
arr1[0:3,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [27]:
arr1[2:4,0:2]

array([[ 6,  7],
       [ 9, 10]])

# Indexing with Boolean arrays

In [28]:
# masking
#  boolean Indecing

In [29]:
arr2 = np.arange(12).reshape(3,4)

In [30]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
10 > 5

True

In [33]:
arr2> 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [37]:
(arr2 % 2 == 0) | (arr2 % 3 == 0)

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [38]:
(arr2 % 2 == 0) & (arr2 % 3 == 0)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [39]:
arr2[(arr2 % 2 == 0) & (arr2 % 3 == 0)]

array([0, 6])

In [40]:
arr2[arr2> 5]

array([ 6,  7,  8,  9, 10, 11])

# Universal function

In [42]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])

In [43]:
a

array([11, 22, 33, 44, 55])

In [44]:
b

array([1, 2, 3, 4, 5])

In [45]:
a + b

array([12, 24, 36, 48, 60])

In [46]:
a - b

array([10, 20, 30, 40, 50])

In [47]:
a * b

array([ 11,  44,  99, 176, 275])

In [48]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4])

In [57]:
# a * b #this will throw error  could not be broadcast

In [62]:
# /HW
1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


1. 'Priya', 'Rohit', 'Aryan'
2. 'Riya','Devanshi'
3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
4. 'Avni'
5. 'Neha'

2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
1. find all scores > 50
2. find all scores <35

SyntaxError: invalid syntax (2311207153.py, line 1)

In [74]:
score = np.random.randint(10,100,15).reshape(5,3)
1. find all scores > 50
2. find all scores <35


In [75]:
score

array([[25, 35, 36],
       [52, 54, 14],
       [10, 49, 66],
       [87, 60, 20],
       [13, 67, 24]])

In [78]:
score<=100 & score>=75

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()