In [12]:
import numpy as np

In [13]:
data = np.loadtxt('fitbit.txt',dtype='str')

In [14]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [15]:
data.shape #27rows and 7features

(26, 7)

In [16]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [17]:
data[1]

array(['07-10-2017', '7167', '200', '208', '6', '0', '68'], dtype='<U10')

In [18]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [19]:
 date ,  step_count ,  mood ,  calories_burned ,hours_of_sleep ,  bool_of_active ,  weight_kg = data.T 

In [20]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [21]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [22]:
step_count.dtype

dtype('<U10')

In [23]:
step_count = np.array(step_count,dtype='int')

In [24]:
step_count.dtype

dtype('int32')

In [25]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [27]:
calories_burned  = np.array(calories_burned,dtype='int')
hours_of_sleep = np.array(hours_of_sleep,dtype='int')
weight_kg = np.array(weight_kg,dtype='int')

In [28]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [31]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [32]:
# replacing the numbers to string values
# data cleaning , munging

In [36]:
mood[mood == '100'] = "Sad"
mood[mood == '200'] = "Neutral"
mood[mood == '300'] = "happy"

In [37]:
mood

array(['Neutral', 'Neutral', 'happy', 'Sad', 'happy', 'happy', 'Sad',
       'Neutral', 'Neutral', 'happy', 'happy', 'happy', 'happy',
       'Neutral', 'Neutral', 'Neutral', 'happy', 'happy', 'Sad', 'Sad',
       'happy', 'happy', 'happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U10')

In [44]:
# ?finding max steps count

In [38]:
np.mean(step_count)

7344.461538461538

In [45]:
# finding the date of max count 

In [39]:
np.argmax(step_count)

5

In [40]:
step_count[5]

9875

In [42]:
date[5]

'11-10-2017'

In [46]:
# most freq mood

In [47]:
mood == 'Sad'

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [48]:
mood[mood == 'Sad']

array(['Sad', 'Sad', 'Sad', 'Sad', 'Sad'], dtype='<U10')

In [49]:
len(mood[mood == 'Sad'])

5

In [50]:
len(mood[mood == 'Neutral'])

9

In [52]:
len((mood[mood == 'happy']))

12

In [53]:
np.unique(mood,return_counts=True)

(array(['Neutral', 'Sad', 'happy'], dtype='<U10'),
 array([ 9,  5, 12], dtype=int64))

# steps counts relation with mood

In [55]:
np.mean(step_count[mood=='happy'])

9173.0

In [56]:
np.mean(step_count[mood=='Sad'])

4528.6

In [57]:
np.mean(step_count[mood=='Neutral'])

6470.777777777777

In [60]:
np.unique(mood[step_count > 6000],return_counts=True)

(array(['Neutral', 'happy'], dtype='<U10'), array([ 6, 12], dtype=int64))

In [62]:
np.unique(mood[step_count < 6000],return_counts=True)

(array(['Neutral', 'Sad'], dtype='<U10'), array([3, 5], dtype=int64))