In [1]:
import numpy as np

In [2]:
# loadingh the data into numpy

In [3]:
# numpy can handle only homogenous data type
# so we have to convert everythibg to string as it is the most suited one
# later we have to convert back to other data type for calcu
# np.loadtxt('fitbit.txt')

In [4]:
data  = np.loadtxt('fitbit.txt',dtype='str')

In [5]:
print(data)

[['06-10-2017' '5464' '200' '181' '6' '0' '68']
 ['07-10-2017' '7167' '200' '208' '6' '0' '68']
 ['08-10-2017' '9874' '300' '341' '5' '0' '68']
 ['09-10-2017' '4969' '100' '190' '8' '0' '68']
 ['10-10-2017' '8538' '300' '307' '5' '0' '68']
 ['11-10-2017' '9875' '300' '302' '5' '0' '68']
 ['12-10-2017' '4662' '100' '198' '8' '0' '68']
 ['13-10-2017' '6310' '200' '201' '6' '0' '68']
 ['14-10-2017' '7556' '200' '195' '6' '0' '68']
 ['15-10-2017' '9073' '300' '327' '5' '0' '68']
 ['16-10-2017' '9690' '300' '331' '5' '0' '68']
 ['17-10-2017' '9146' '300' '318' '5' '0' '68']
 ['18-10-2017' '9752' '300' '344' '5' '0' '68']
 ['19-10-2017' '6974' '200' '204' '6' '0' '68']
 ['20-10-2017' '5619' '200' '180' '6' '0' '68']
 ['21-10-2017' '6889' '200' '201' '6' '0' '68']
 ['22-10-2017' '8616' '300' '329' '5' '0' '68']
 ['23-10-2017' '9131' '300' '315' '5' '0' '68']
 ['24-10-2017' '4211' '100' '197' '8' '0' '68']
 ['25-10-2017' '4291' '100' '184' '8' '0' '68']
 ['26-10-2017' '8569' '300' '328' '5' '0

In [6]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [7]:
#  now data looks like a numpy arraty
# we can check the parameters

In [8]:
data.shape  # rows is data and column is features

(26, 7)

In [9]:
data.size

182

In [10]:
data.ndim

2

# data Cleaning

In [11]:
# extracting the columns and chnagin the data types

In [12]:
data[0] #extracting 1st row

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [13]:
# transposing the data and tking the 1st row will give the 1st column

In [14]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [15]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [16]:
# using transpose , packing and unpacking concepts

In [17]:
date,  step_count, mood ,calories_burned, hours_of_sleep, bool_of_active, weight_kg =   data.T              

In [18]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [19]:
data.dtype

dtype('<U10')

In [20]:
step_count.dtype

dtype('<U10')

In [21]:
# changing the  data types of each row after we got the transpose


In [22]:
step_count = np.array(step_count,dtype='int')

In [23]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [24]:
step_count.dtype

dtype('int32')

In [25]:
calories_burned  = np.array(calories_burned,dtype='int')
hours_of_sleep  = np.array(hours_of_sleep,dtype='int')
weight_kg  = np.array(weight_kg,dtype='int')

In [26]:
# taking cloaser look into the data under mood column

In [27]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [28]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [29]:
# there is no variation in data type
# consulting with the team
# we come to know that its not anumerical data but is a categorincal data 

In [30]:
# we can check the uique values
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [31]:
# again we have to contact the team for values represented by each code

In [32]:
'''
100 sad
200 neutral
300 happy
'''

'\n100 sad\n200 neutral\n300 happy\n'

In [33]:
# we will convert the numerical data to categorical datya 

In [34]:
# using masking

In [35]:
# we will get all 300 in the mood as true
mood == '300'

array([False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False,  True,  True,  True, False, False, False])

In [36]:
mood[mood == '300'] #getting the actual values

array(['300', '300', '300', '300', '300', '300', '300', '300', '300',
       '300', '300', '300'], dtype='<U10')

In [37]:
# replacing the values to Happy , where the mood is 300
mood[mood == '300'] = 'Happy'

In [38]:
mood

array(['200', '200', 'Happy', '100', 'Happy', 'Happy', '100', '200',
       '200', 'Happy', 'Happy', 'Happy', 'Happy', '200', '200', '200',
       'Happy', 'Happy', '100', '100', 'Happy', 'Happy', 'Happy', '100',
       '200', '200'], dtype='<U10')

In [39]:
# similarly replacing for 100 and 200

In [40]:
mood[mood == '100'] = 'Sad'
mood[mood == '200'] = 'Neutral'

In [41]:
mood

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U10')

In [42]:
bool_of_active

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
      dtype='<U10')

In [43]:
mood[mood == '300'] = 'Happy'

# data Analysing

In [44]:
# insights from the data

# steps count

In [45]:
# max steps count
np.max(step_count)

9875

In [46]:
np.mean(step_count)

7344.461538461538

In [47]:
# data on which max steps done

In [48]:
np.argmax(step_count)

5

In [49]:
# cross checking the value
step_count[5]

9875

In [50]:
# finding the date corr to the argumnent/index = 5
date[5]


'11-10-2017'

# feq of mood

In [51]:
# getting all the mood
mood == 'Sad'
mood[mood == 'Sad']

array(['Sad', 'Sad', 'Sad', 'Sad', 'Sad'], dtype='<U10')

In [52]:
mood == 'Neutral'
mood[mood == 'Neutral']

array(['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Neutral', 'Neutral', 'Neutral'], dtype='<U10')

In [53]:
mood == 'Happy'
mood[mood == 'Happy']

array(['Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy'], dtype='<U10')

In [54]:
# findin the length/ count of each mood

print(len(mood[mood == 'Sad']))
print(len(mood[mood == 'Neutral']))
print(len(mood[mood == 'Happy']))



5
9
12


In [55]:
# taking help of fun to do the same as above
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([12,  9,  5], dtype=int64))

# does the stepcout changes with the mood?

In [56]:
# steps count when the mood is Happy
step_count[mood == 'Happy']


# checking the mean to get the overall idea
np.mean(step_count[mood == 'Happy'])

9173.0

In [57]:
# steps count when the mood is Happy
step_count[mood == 'Sad']

# checking the mean to get the overall idea
np.mean(step_count[mood == 'Sad'])

4528.6

In [58]:
# steps count when the mood is Happy
step_count[mood == 'Neutral']

# checking the mean to get the overall idea
np.mean(step_count[mood == 'Neutral'])

6470.777777777777

# checking the moods when the steps count was higher

In [59]:
np.unique(mood[step_count>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([12,  9,  5], dtype=int64))

In [60]:
mood[step_count>4000]

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U10')